### ISSUE TITLE
Pep fordwards empty body {} when GET requests include content-type header

### ISSUE THREAD

**Issue by mcarracedo** [telefonicaid/fiware-pep-steelskin#222]
If someone accidentally includes Content-type header in a GET request to PEP-CB, PEP fordwards the requests with "body":"{}"

The pep log shows the following (note that auth-token header has been removed for the shake of readability):
{"uri":"http://localhost:1026/v1/contextEntities/type/Room/id/Room1","qs":{},"method":"GET","headers":{"x-forwarded-for":"195.235.92.36","host":"nodes_10027_to_10026","connection":"close","accept":"application/json","cache-control":"no-cache","fiware-service":"tecnoport","fiware-servicepath":"/","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36","content-type":"application/json","accept-encoding":"gzip, deflate, sdch","accept-language":"es-ES,es;q=0.8,en;q=0.6"},"body":"{}"}

This fact provokes that CB answers to the request a 400 error:
'{
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "Sorry, no request treating object found for RequestType /AllEntitiesWithTypeAndId/"
  }
}

Indeed, there isn't any bug at all, but it would be desirable for a user to get more info about the error or to avoid this error if possible.

**Comment by fgalan** [comment]
Is this bug needed to be fixed for IoTP v2.0?

**Comment by dmoranj** [comment]
I'm not sure this is a bug at all. A request with 'Content-type: application/json' is expected to contain a JSON body; if it doesn't, the problem is the request itself. In this case, the response the user should expect is a 400 Code error (although I have to admit the description is not clear in this case). Considering thi, the priority of the bug and the fact that the solution cost would be much bigger than the benfit (as it would imply modifying how Express parses the incoming JSON objects or writing a complete new JSON middleware), I think we should discard this bug (unless the priority rises to a level where it make sense again to consider it).

**Comment by dmoranj** [comment]
NTC
